#!/bin/bash

if screen -list | grep -q "chariotRegisterAgent"; then
  screen -ls | grep -E "chariotRegisterAgent" | cut -d. -f1 | awk '{print }' | xargs kill 2> /dev/null
    echo "Chariot register agent stopped."
else
  echo "Chariot register agent isn't running."
fi

